### ISSUE TITLE
Choices are not intuitive - 1 vs Yes

### ISSUE THREAD

**Issue by mraible** [oktadeveloper/okta-cli#30]
I thought I had to type some form of "Yes". It took me a while to realize it was 1 or 2. 😅

```
okta register
An existing Okta Organization (https://dev-896939.okta.com) was found in /Users/mraible/.okta/okta.yaml
Overwrite configuration file?
> 1: Yes
> 2: No
Enter your choice [Yes]: y

Invalid choice, try again

Overwrite configuration file?
> 1: Yes
> 2: No
Enter your choice [Yes]: Yes

Invalid choice, try again

Overwrite configuration file?
> 1: Yes
> 2: No
Enter your choice [Yes]: yes

Invalid choice, try again

Overwrite configuration file?
> 1: Yes
> 2: No
Enter your choice [Yes]: Y

Invalid choice, try again

Overwrite configuration file?
```

Related: If I use `[URL1,URL2]` for redirect URIs, it fails.

```
➜  ionic-social git:(master) okta apps create
Application name [ionic-social]: Ionic Social
Type of Application
(The Okta CLI only supports a subset of application types and properties):
> 1: Web
> 2: Single Page App
> 3: Native App (mobile)
> 4: Service (Machine-to-Machine)
Enter your choice [Web]: 3
Redirect URI
Common defaults:
 Reverse Domain name - com.example:/callback
Enter your Redirect URI [com.okta.dev-317297:/callback]: [com.okta.dev-317297:/callback,http://localhost:8100]
Configuring a new OIDC Application, almost done:
\

An error occurred if you need more detail use the '--verbose' option

HTTP 400, Okta E0000001 (Api validation failed: redirect_uris - redirect_uris: ''redirect_uris'' must be an array of absolute URIs.), ErrorId oaenTDlC5_mQCaQhjgbe8JTpg
```

Using `URL1,URL2` works. 

Finally, how do I add/edit logout redirect URIs? It doesn't seem to be an option.

**Comment by mraible** [comment]
Doh! Multiple login redirects don't seem to be supported. When I look at the created app in my browser, I see:

```
com.okta.dev-317297:/callback,http://localhost:8100/callback
```

On a single line.

**Comment by bdemers** [comment]
What do you think would work best? entering them in comma separated? or prompting the user to add another one or continue?
Comma-separated would be easy to add, and might cause less friction for folks that only have on callback URL?

**Comment by mraible** [comment]
Either technique works for me! The only issue with comma-separated is `[URL1,URL2]` seems (to me) like the best way to enter them, but that doesn't work. If the string starts with `[`, we should detect that and tell the user not to use it.

**Comment by bdemers** [comment]
Good call, it's easy enough to validate the URLs
